<template>
  <div>
    <div>
      <img
        class="logo"
        src="../assets/logoWelcome.png"
        alt="OriginTrail"
        width="300"
        height="300px"
      />
    </div>
  </div>
</template>
